# Base image https://hub.docker.com/u/rocker/
FROM rocker/r-base:latest

## Install knitr and pander packages
RUN install2.r --error \
    knitr \
    pander \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

## copy files
COPY install_packages.R /install_packages.R

## install R-packages
RUN Rscript /install_packages.R

