# Base image 
FROM graydon/base-r-tidyverse:latest

# install the linux libraries needed for plumber
RUN apt-get update -qq && apt-get install -y \
  libssl-dev \
  libcurl4-gnutls-dev

# create directories
RUN mkdir -p /01_data
RUN mkdir -p /02_code
RUN mkdir -p /03_output

## copy files
COPY myScript.R myScript.R

# open port 80 to traffic
EXPOSE 80

## run the script
CMD Rscript myScript.R
